[package]
name = "tws-rust"
version = "0.1.0"
authors = ["Peter Cai <peter@typeblog.net>"]

[dependencies]
base64 = "0.6"
bytes = "0.4"
error-chain = "0.11"
futures = "0.1"
hmac = "0.5"
rand = "0.4"
sha2 = "0.7"
time = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
websocket = "0.20"